# Generated by Django 5.0.3 on 2024-04-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='registration_data',
            new_name='registration_date',
        ),
    ]
